/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ktdiedrich_math_NativeDijkstra */

#ifndef _Included_ktdiedrich_math_NativeDijkstra
#define _Included_ktdiedrich_math_NativeDijkstra
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ktdiedrich_math_NativeDijkstra
 * Method:    dijkstra
 * Signature: ([Lktdiedrich/imagek/GraphNode;I)V
 */
JNIEXPORT void JNICALL Java_ktdiedrich_math_NativeDijkstra_dijkstra
  (JNIEnv *, jclass, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
