/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ktdiedrich_math_NativeCall */

#ifndef _Included_ktdiedrich_math_NativeCall
#define _Included_ktdiedrich_math_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ktdiedrich_math_NativeCall
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ktdiedrich_math_NativeCall_greeting
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
